dist: trusty
language: rust
cache: cargo
env: TARGET=arm-unknown-linux-gnueabihf CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc
before_deploy: ci/before_deploy.sh
deploy:
  file: picat-$TRAVIS_TAG-$TARGET.tar.gz 
  on:
    repo: creinholdsson/picat
  provider: releases

