[package]
name = "picat"
version = "0.3.0"
authors = ["Christofer R"]
edition = "2018"

[dependencies]
rppal = "0.11.3"
chrono = "0.4.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"